name: 'build-test'

on:
  push:
  pull_request:
    
jobs:
  build_and_test:
    name: '${{ matrix.os }}: build and unit tests'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - uses: lukka/get-cmake@latest

      - name: Setup anew (or from cache) vcpkg
        uses: lukka/run-vcpkg@v11 

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.os == 'ubuntu-latest' && 'nix-x64-debug' || matrix.os == 'macos-latest' && 'macos-x64-debug' || matrix.os == 'windows-latest' && 'msvc-x64-debug' }}
          buildPreset: ${{ matrix.os == 'ubuntu-latest' && 'nix-x64-debug' || matrix.os == 'macos-latest' && 'macos-x64-debug' || matrix.os == 'windows-latest' && 'msvc-x64-debug' }}
          testPreset: ${{ matrix.os == 'ubuntu-latest' && 'nix-x64-test' || matrix.os == 'macos-latest' && 'macos-x64-test' || matrix.os == 'windows-latest' && 'msvc-x64-test' }}
